print ("Remelyn Zulueta Tampol")
print ("Purok 3, Barangay, Bagtingon, Buenavista, Marinduque")
print ("November 8, 2001")
print ("Institute of Information Systems and Technology")
print ("BSIT")
print ("Second Year College")
print ("B")
print ("Singing")
print ("Dancing")
print ("Playing Guitar")
print ("Volleyball")
print ("Badminton")
